import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Basir',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Arcteryx 始祖鳥 LOGO尼龍腰帶 黑',
      category: 'Belt',
      image: '/images/p1.jpeg',
      price: 1500,
      countInStock: 10,
      brand: 'Arcteryx',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Arcteryx 始祖鳥 短袖休閒Tee 白',
      category: 'Shirts',
      image: '/images/p2.jpeg',
      price: 1600,
      countInStock: 10,
      brand: 'Arcteryx',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Arcteryx 始祖鳥 32L多功能背包 黑',
      category: 'Bag',
      image: '/images/p3.jpeg',
      price: 5680,
      countInStock: 10,
      brand: 'Arcteryx',
      rating: 4,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Arcteryx 始祖鳥 休閒Tee 翠鳥藍',
      category: 'Shirts',
      image: '/images/p4.jpeg',
      price: 1600,
      countInStock: 10,
      brand: 'Arcteryx',
      rating: 3.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Arcteryx 始祖鳥 遮陽帽 黑',
      category: 'Hat',
      image: '/images/p5.jpeg',
      price: 2450,
      countInStock: 10,
      brand: 'Arcteryx',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'The North Face 斜背包',
      category: 'Bag',
      image: '/images/p6.jpeg',
      price: 1500,
      countInStock: 10,
      brand: 'The North Face',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'The North Face Face 男 短袖T恤 黑',
      category: 'Shirts',
      image: '/images/p7.jpeg',
      price: 1480,
      countInStock: 10,
      brand: 'The North Face',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'The North Face 女 短袖T恤 黑',
      category: 'Shirts',
      image: '/images/p8.jpeg',
      price: 1480,
      countInStock: 10,
      brand: 'The North Face',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'SALOMON X ULTRA 4 低筒登山鞋',
      category: 'Shoes',
      image: '/images/p9.jpeg',
      price: 5300,
      countInStock: 10,
      brand: 'SALOMON',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Mammut LOGO短袖上衣 白',
      category: 'Shirts',
      image: '/images/p10.jpeg',
      price: 1690,
      countInStock: 10,
      brand: 'Mammut',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Mammut LOGO短袖上衣 海洋藍',
      category: 'Shirts',
      image: '/images/p11.jpeg',
      price: 1690,
      countInStock: 10,
      brand: 'Mammut',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Mammut LOGO短袖上衣 黑',
      category: 'Shirts',
      image: '/images/p12.jpeg',
      price: 1690,
      countInStock: 10,
      brand: 'Mammut',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Mammut Ducan 24L 輕量健行後背包',
      category: 'Bag',
      image: '/images/p13.jpeg',
      price: 5380,
      countInStock: 10,
      brand: 'Mammut',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Mammut 輕量健行後背包 花崗岩灰',
      category: 'Bag',
      image: '/images/p14.jpeg',
      price: 9700,
      countInStock: 10,
      brand: 'Mammut',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'MAMMUT 超輕量防水防風外套 藏青',
      category: 'jacket',
      image: '/images/p15.jpeg',
      price: 8800,
      countInStock: 10,
      brand: 'Mammut',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};
export default data;
